[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
optimizer_runs = 200
verbosity = 3 # display errors
match_contract = "Unit" # only runs unit tests by default
sizes = true

[profile.CI] # run via FOUNDRY_PROFILE=CI foundry test
fs_permissions = [{ access = "read", path = "./node_modules/@jbx-protocol/juice-contracts-v3/deployments/mainnet"}] # Get the deployment addresses for forking
match_contract = "Unit || Fork" 

# See more config options https://github.com/foundry-rs/foundry/tree/master/config